// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      studentId: json['student_id'] as String?,
      studentCode: json['student_code'] as String?,
      name: json['name'] as String?,
      birthday: json['birthday'] as String?,
      sex: json['sex'] as String?,
      religion: json['religion'] as String?,
      bloodGroup: json['blood_group'] as String?,
      address: json['address'] as String?,
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      password: json['password'] as String?,
      parentId: json['parent_id'] as String?,
      dormitoryId: json['dormitory_id'] as String?,
      transportId: json['transport_id'] as String?,
      dormitoryRoomNumber: json['dormitory_room_number'] as String?,
      authenticationKey: json['authentication_key'] as String?,
      fatherName: json['father_name'] as String?,
      fatherPhone: json['father_phone'] as String?,
      motherName: json['mother_name'] as String?,
      motherPhone: json['mother_phone'] as String?,
      guardianName: json['guardian_name'] as String?,
      guardianPhone: json['guardian_phone'] as String?,
      caste: json['caste'] as String?,
      aadharNumber: json['aadhar_number'] as String?,
      uploadCertificates: json['upload_certificates'],
      fatherOccupation: json['father_occupation'] as String?,
      motherOccupation: json['mother_occupation'] as String?,
      disabilityStatus: json['disability_status'] as String?,
      disabilityDescription: json['disability_description'] as String?,
      notification: json['notification'] as String?,
      dateAdmission: json['date_admission'],
      status: json['status'] as String?,
      ip: json['ip'],
      deviceId: json['device_id'],
      seenNotes: json['seen_notes'],
      seenVideo: json['seen_video'] as String?,
      seenAudio: json['seen_audio'],
      courseId: json['course_id'],
      classId: json['class_id'] as String?,
      sectionId: json['section_id'] as String?,
      utype: json['utype'] as String?,
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'student_id': instance.studentId,
      'student_code': instance.studentCode,
      'name': instance.name,
      'birthday': instance.birthday,
      'sex': instance.sex,
      'religion': instance.religion,
      'blood_group': instance.bloodGroup,
      'address': instance.address,
      'phone': instance.phone,
      'email': instance.email,
      'password': instance.password,
      'parent_id': instance.parentId,
      'dormitory_id': instance.dormitoryId,
      'transport_id': instance.transportId,
      'dormitory_room_number': instance.dormitoryRoomNumber,
      'authentication_key': instance.authenticationKey,
      'father_name': instance.fatherName,
      'father_phone': instance.fatherPhone,
      'mother_name': instance.motherName,
      'mother_phone': instance.motherPhone,
      'guardian_name': instance.guardianName,
      'guardian_phone': instance.guardianPhone,
      'caste': instance.caste,
      'aadhar_number': instance.aadharNumber,
      'upload_certificates': instance.uploadCertificates,
      'father_occupation': instance.fatherOccupation,
      'mother_occupation': instance.motherOccupation,
      'disability_status': instance.disabilityStatus,
      'disability_description': instance.disabilityDescription,
      'notification': instance.notification,
      'date_admission': instance.dateAdmission,
      'status': instance.status,
      'ip': instance.ip,
      'device_id': instance.deviceId,
      'seen_notes': instance.seenNotes,
      'seen_video': instance.seenVideo,
      'seen_audio': instance.seenAudio,
      'class_id': instance.classId,
      'section_id': instance.sectionId,
      'utype': instance.utype,
    };
